version: "3.9"

services:
  backend:
    container_name: ai_knowledge_api
    build:
      context: .             # usa la raíz del proyecto (donde está Dockerfile)
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app               # monta el proyecto actual dentro del contenedor
    restart: always
